config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "user_root" => "dashboards#show"
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    resources :messages, only: [:index]
  end

  # teams for users: only index & show
  # teams for developpers: all except destroy protected by pundit >> admin feature with devise
  resources :teams, only: [:index, :show, :new, :create, :edit, :update] do
    # new messages displayed in requests through a form
    resources :requests, only: [:index, :show, :new, :create, :edit, :update]
    # scores displayed in games (or teams)
    resources :games, only: [:index, :show, :new, :create, :edit, :update]
  end

  resources :messages, only: :create

  resources :profiles, only: :show

  get '/dashboard', to: 'dashboards#show'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    <p>@Derby Team</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-derby-match">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1 class="white">DERBY MATCH<%= image_tag "logo_simple.png" %></h1>

  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= "active" if controller_name == "dashboards" %>">
        <%= link_to "DASHBOARD", dashboard_path, class: "nav-link logged-nav" %>
      </li>
      <li class="nav-item <%= "active" if controller_name == "teams" %>">
        <%= link_to "SEARCH", teams_path, class: "nav-link logged-nav" %>
      </li>
      <li class="nav-item <%= "active" if controller_name == "requests" %>">
        <%= link_to "REQUESTS", team_requests_path(current_user.team), class: "nav-link logged-nav" %>
      </li>
      <li class="nav-item <%= "active" if controller_name == "games" %>">
        <%= link_to "GAMES", team_games_path(current_user.team), class: "nav-link logged-nav" %>
      </li>
      <li class="nav-item dropdown">
        <% if current_user.photo? %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag 'avatar.jpeg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Your profile",
          edit_user_registration_path, class: "nav-link" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </div>
      </li>
    <% else %>

      <!-- Login link (when logged out) -->
      <%= link_to 'SIGN UP', new_user_registration_path, class: "nav-link log-in-nav" %>
      <%= link_to 'LOG IN', new_user_session_path, class: "nav-link log-in-nav" %>
    <% end %>
      <div class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Find a Team", teams_path, class: "dropdown-item" %>
          <%= link_to "Request", "#", class: "dropdown-item" %>
        </div>
      </div>
    </ul>
  </div>
</div>