config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "user_root" => "dashboards#show"
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    resources :messages, only: [:index]
  end

  # teams for users: only index & show
  # teams for developpers: all except destroy protected by pundit >> admin feature with devise
  resources :teams, only: [:index, :show, :new, :create, :edit, :update] do
    # new messages displayed in requests through a form
    resources :requests, only: [:index, :show, :new, :create, :edit, :update]
    # scores displayed in games (or teams)
    resources :games, only: [:index, :show, :new, :create, :edit, :update]
  end

  resources :messages, only: :create

  resources :profiles, only: :show

  get '/dashboard', to: 'dashboards#show'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :team
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_one :game

  validates :team_id, presence: true
  validates :user_id, presence: true
  validates :status, presence: true
  validates :start_date, presence: true

  scope :accepted, -> { where(status: "accepted") }
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :update]

  def index
    @requests_sent = policy_scope(Request).where(user: current_user)
    @pending_requests_sent = @requests_sent.where(status: "pending")
    @declined_requests_sent = @requests_sent.where(status: "declined")
    @accepted_requests_sent = @requests_sent.where(status: "accepted")
    @cancelled_requests_sent = @requests_sent.where(status: "cancelled")

    @requests_received = Request.all.select do |request|
      request.team.user == current_user
    end
    @pending_requests_received = @requests_received.select do |request|
      request.status == "pending"
    end
    @accepted_requests_received = @requests_received.select do |request|
      request.status == "accepted"
    end
    @declined_requests_received = @requests_received.select do |request|
      request.status == "declined"
    end
    @cancelled_requests_received = @requests_received.select do |request|
      request.status == "cancelled"
    end
  end

  def show
    @team = Team.find(params[:team_id])
    @message = Message.new(request: @request)
  end

  def create
    @team = Team.find(params[:team_id])
    authorize @team
    @request = Request.new(request_params)
    @message = Message.new(request_message_params)
    @message.request = @request
    @message.user = current_user
    @request.team = @team
    @request.user = current_user
    @request.status = "pending"
    if params[:request][:at_home] == "0"
      @request.at_home = true
    else
      @request.at_home = false
    end
    @request.end_date = @request.start_date
    @request.save
    @message.save
    if @message.save!
      respond_to do |format|
        format.html { redirect_to team_requests_path(current_user.team) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'teams/show' }
        format.js
      end
    end
  end

  def update
    if params[:commit] == "ACCEPT"
      @request.update(status: params[:status])
      @game = Game.new
      @game.request = @request
      @game.start_date = @request.start_date
      @game.end_date = @request.end_date
      if @game.save!
        respond_to do |format|
          format.html { redirect_to dashboard_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { redirect_to 'teams/show' }
          format.js
        end
      end
    else
      @request.update(status: params[:status])
      if @request.save!
        respond_to do |format|
          format.html { redirect_to dashboard_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { redirect_to 'teams/show' }
          format.js
        end
      end
    end
  end

  private

  def set_request
    @request = Request.find(params[:id])
    authorize @request
  end

  def request_params
    params.require(:request).permit(:start_date, :end_date, :team_id, :user_id, :at_home)
  end

  def request_message_params
    params.require(:request).dig(:message).permit(:content)
  end
end

app/views/requests/_form-message.html.erb
<%= simple_form_for [@request, @message], remote: true, url: messages_path, method: :post do |f| %>
  <%= f.input :content, label: 'Your reply', input_html: { value: '' } %>
  <%= f.input :request_id, as: :hidden %>
  <%= f.button :submit, "SEND",  class: 'my-btn center-right-btn ajax-btn' %>
<% end %>

app/views/requests/_form-update-request.html.erb
<p><%= request.status.upcase %></p>
<% if request.status.upcase == "PENDING" %>
  <% if request.user == current_user %>
    <%= simple_form_for [request.team, request], remote: true, :url => { action: "update" }, method: :patch do |f| %>
      <input type="hidden" value="<%= request.id %>" name="id">
      <input type="hidden" value="cancelled" name="status">
      <%= f.button :submit, value: 'CANCEL', class: "my-btn cancel-decline", id: "decline-button" %>
    <% end %>
  <% else %>
    <%= simple_form_for [request.team, request], :url => { action: "update" }, remote: true, method: :patch do |f| %>
      <input type="hidden" value="<%= request.id %>" name="id">
      <input type="hidden" value="accepted" name="status">
      <%= f.button :submit, value: 'ACCEPT', class: "my-btn", id: "accept-button" %>
    <% end %>

    <%= simple_form_for [request.team, request], :url => { action: "update" }, remote: true, method: :patch do |f| %>
      <input type="hidden" value="<%= request.id %>" name="id">
      <input type="hidden" value="declined" name="status">
      <%= f.button :submit, value: 'DECLINE', class:"my-btn cancel-decline", id: "decline-button" %>
    <% end %>
  <% end %>
<% end %>

app/views/requests/_old-received.html.erb
<div class="old-request request-details">
  <div class="dates text-center">
    <p><%= request.start_date.strftime('%a %d %b %Y') %></p>
  </div>
  <div class="request-content">
    <div class="team">
      <p><%= request.user.team.league.name.upcase %><br><%= request.user.team.name %></p>
      <p>#<%= request.user.team.ranking %></p>
    </div>
    <div class="location">
      <p style="padding-right: 71px;">
        <% if request.at_home == false %>
          <i class="fas fa-home"></i> <%= current_user.team.league.city %>, <%= current_user.team.league.country %>
        <% else %>
          <i class="fas fa-plane"></i> <%= request.user.team.league.city %>, <%= request.user.team.league.country %>
        <% end %>
      </p>
    </div>
    <div class="status">
      <p><br><%= request.status.capitalize %> by you </p>
    </div>
  </div>
</div>

app/views/requests/_old-sent.html.erb
<div class="old-request request-details">
  <div class="dates text-center">
    <p><%= request.start_date.strftime('%a %d %b %Y') %></p>
  </div>
  <div class="request-content">
    <div class="team">
      <p><%= request.team.league.name.upcase %><br><%= request.team.name %></p>
      <p>#<%= request.team.ranking %></p>
    </div>
    <div class="location">
      <p style="padding-right: 71px;">
        <% if request.at_home == false %>
          <i class="fas fa-plane"></i> <%= request.user.team.league.city %>, <%= request.user.team.league.country %>
        <% else %>
          <i class="fas fa-home"></i> <%= current_user.team.league.city %>, <%= current_user.team.league.country %>
        <% end %>
      </p>
    </div>
    <div class="status">
      <p><%= request.status.capitalize %> by you </p>
    </div>
  </div>
</div>

app/views/requests/_one-message.html.erb
<div class="one-message">
  <div class="message-author">
    <p>
      <% if team.user.photo.present? %>
      <%= cl_image_tag(message.user.photo, height: 250, width: 250,crop: :fill, class: "avatar")  %>
      <% else %>
      <%= image_tag 'avatar.jpeg', class: "avatar" %>
      <% end %>
    </p>
    <p class="user-message-name"><%= message.user.derby_name %></p>
    <p class="italic-date"><%= message.created_at.strftime("%b %e, %l:%M %p") %></p>
  </div>
  <div class="message-content">
    <p><%= message.content %></p>
  </div>
  <br>
</div>

app/views/requests/_received.html.erb
<div class="request-details">
  <div class="dates text-center">
    <p><%= request.start_date.strftime('%a %d %b %Y') %></p>
  </div>
  <div class="request-content">
    <div class="team">
      <p><%= request.user.team.league.name.upcase %><br><%= request.user.team.name %></p>
      <p>#<%= request.user.team.ranking %></p>
    </div>
    <div class="location">
      <p>
        <% if request.at_home == false %>
          <i class="fas fa-home"></i> <%= current_user.team.league.city %>, <%= current_user.team.league.country %>
        <% else %>
          <i class="fas fa-plane"></i> <%= request.user.team.league.city %>, <%= request.user.team.league.country %>
        <% end %>
      </p>
    </div>
    <div class="link">
      <p><%= link_to "GET MORE DETAILS", team_request_path(request.team, request), class:"my-btn" %></p>
    </div>
  </div>
</div>

app/views/requests/_sent.html.erb
<div class="request-details">
  <div class="dates text-center">
    <p><%= request.start_date.strftime('%a %d %b %Y') %></p>
  </div>
  <div class="request-content">
    <div class="team">
      <p><%= request.team.league.name.upcase %><br><%= request.team.name %></p>
      <p>#<%= request.team.ranking %></p>
    </div>
    <div class="location">
      <p>
        <% if request.at_home == false %>
          <i class="fas fa-plane"></i> <%= request.team.league.city %>, <%= request.team.league.country %>
        <% else %>
          <i class="fas fa-home"></i> <%= current_user.team.league.city %>, <%= current_user.team.league.country %>
        <% end %>
      </p>
    </div>
    <div class="link">
      <p><%= link_to "GET MORE DETAILS", team_request_path(request.team, request), class:"my-btn" %></p>
    </div>
  </div>
</div>

app/views/requests/create.js.erb
// empty but necessary to pretend like the sweetalert is setup
window.location.pathname = '/teams/<%= current_user.team.id %>/requests'

app/views/requests/index.html.erb
<div class="container">
    <h2 class="text-center dashboard-title white">Requests for <%= current_user.team.name %></h2>
  <!-- pending requests: -->
  <% if @pending_requests_received.present? || @pending_requests_sent.present? %>
    <div class="pending-requests">
      <h3 class="text-center white">Pending requests</h3>
      <% @pending_requests_received.each do |request| %>
        <%= render 'received', request: request %>
      <% end %>
      <% @pending_requests_sent.each do |request| %>
        <%= render 'sent', request: request %>
      <% end %>
    </div>
  <% else %>
      <h3 class="text-center white">No pending request</h3>
  <% end %>

  <!-- cancelled & declined requests -->
  <div class="old-requests">
    <% if @declined_requests_sent.present? || @declined_requests_received.present? || @cancelled_requests_sent.present? || @cancelled_requests_received.present? %>
      <h3 class="text-center margin">Cancelled and declined requests</h3>
      <% @declined_requests_received.each do |request| %>
        <%= render 'old-received', request: request %>
      <% end %>

      <% @declined_requests_sent.each do |request| %>
        <%= render 'old-sent', request: request %>
      <% end %>

      <% @cancelled_requests_received.each do |request| %>
        <%= render 'old-received', request: request %>
      <% end %>

      <% @cancelled_requests_sent.each do |request| %>
        <%= render 'old-sent', request: request %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/requests/show.html.erb
<!-- if it's a request i've sent -->
<div class="container">
  <% if @request.user == current_user %>
    <h2 class="text-center title-request white">Request to <%= @team.name.upcase %></h2>
    <div class="grid-request">
      <div class="card">
        <div class="team-img">
          <p><%= image_tag(@team.photo, height: 250, width: 250,crop: :fill) %></p>
        </div>
        <div class="team-infos">
          <h2><%= @team.league.name.upcase %></h2>
          <p><%= @team.name %> <span class="">(#<%= @team.ranking %>)</span></p>
          <br>
          <p><i class="far fa-user"></i> <%= @team.user.derby_name %></p>
        </div>

        <div class="request-infos">
          <p><i class="far fa-calendar-alt"></i> <%= @request.start_date.strftime('%a %d %b %Y') %></p>
          <p>
            <% if @request.at_home == true %>
              <i class="fas fa-home"></i> <%= current_user.team.league.city %>, <%= current_user.team.league.country %>
            <% else %>
              <i class="fas fa-plane"></i> <%= @team.league.city %>, <%= @team.league.country %>
            <% end %>
          </p>
        </div>
        <div class="request-status" id="request-status">
          <div id='<%= "update-request-form-#{@request.id}" %>'>
            <%= render 'form-update-request', request: @request %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container message-container">
      <div class="message-form form-request-center">
        <%= render 'requests/form-message', request: @request, message: @message %>
      </div>
      <div class="chat-message">
        <div class="messages">
          <% @request.messages.each do |message| %>
            <%= render 'requests/one-message', team: @team, message: message %>
          <% end %>
        </div>
      </div>
  </div>

  <!-- if it's a request i've received -->
  <% else %>
  <div class="container">
    <h2 class="text-center title-request white">Request from <%= @request.user.team.name %></h2>
    <div class="grid-request">
      <div class="card">
        <div class="team-img">
          <p><%= image_tag(@request.user.team.photo, height: 250, width: 250,crop: :fill) %></p>
        </div>
        <div class="team-infos">
          <h2><%= @request.user.team.league.name.upcase %></h2>
          <p><%= @request.user.team.name %> <span class="">(#<%= @request.user.team.ranking %>)</span></p>
          <br>
          <p><i class="far fa-user"></i> <%= @request.user.team.user.derby_name %></p>
        </div>

        <div class="request-infos">
          <p><i class="far fa-calendar-alt"></i> <%= @request.start_date.strftime('%a %d %b %Y') %></p>
          <p>
             <% if @request.at_home == true %>
              <i class="fas fa-home"></i> <%= @current_user.team.league.city %>, <%= @current_user.team.league.country %>
            <% else %>
              <i class="fas fa-plane"></i> <%= @current_user.team.league.city %>, <%= @current_user.team.league.country %>
            <% end %>
          </p>
        </div>
         <div class="request-status" id="request-status">
            <div id='<%= "update-request-form-#{@request.id}" %>'>
              <%= render 'form-update-request', request: @request %>
            </div>
        </div>
      </div>
    </div>

    <div class="container message-container">
      <div class="message-form form-request-center">
        <%= render 'requests/form-message', request: @request, message: @message %>
      </div>
      <div class="chat-message">
        <div class="messages" id="messages">
          <% @request.messages.each do |message| %>
            <%= render 'requests/one-message', team: @team, message: message %>
          <% end %>
        </div>
      </div>
      <!-- <div class="message-form form-request-center"> -->
        <%#= simple_form_for [@request, @message], remote: true, url: messages_path, method: :post do |f| %>
          <%#= f.input :content, label: 'Your reply' %>
          <%#= f.input :request_id, as: :hidden %>
          <%#= f.button :submit, "Send Message",  class: 'my-btn center-right-btn' %>
        <%# end %>
      <!-- </div> -->
    </div>
  <% end %>
</div>

app/views/requests/update.js.erb
function refreshPartial(html, form_id) {
  const partial = document.getElementById(form_id);
  partial.innerHTML = html;
}

function wait(ms){
   var start = new Date().getTime();
   var end = start;
   while(end < start + ms) {
     end = new Date().getTime();
  }
}

refreshPartial("<%= j render 'form-update-request', request: @request %>", '<%= "update-request-form-#{@request.id}" %>');
<% if @request.status == "accepted" %>
  window.location.pathname = '/teams/<%= current_user.team.id %>/games/<%= current_user.team.games.last.id %>'
<% end %>