config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "user_root" => "dashboards#show"
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update] do
    resources :messages, only: [:index]
  end

  # teams for users: only index & show
  # teams for developpers: all except destroy protected by pundit >> admin feature with devise
  resources :teams, only: [:index, :show, :new, :create, :edit, :update] do
    # new messages displayed in requests through a form
    resources :requests, only: [:index, :show, :new, :create, :edit, :update]
    # scores displayed in games (or teams)
    resources :games, only: [:index, :show, :new, :create, :edit, :update]
  end

  resources :messages, only: :create

  resources :profiles, only: :show

  get '/dashboard', to: 'dashboards#show'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized
  after_action :verify_policy_scoped

  def show
    authorize :dashboard, :show?
    @requests = policy_scope(Request).where(user: current_user)
    @games = policy_scope(Game).where(user: current_user)
    @teams = policy_scope(Team)

    user_league_teams = current_user.team.league.teams
    teams = @teams.reject { |team| user_league_teams.include?(team) }

    user_ranking = current_user.team.ranking
    # array of hashes (with team_id: & ranking_difference:)
    ranking_differences = []
    teams.each do |team|
      rankings = []
      rankings << team.ranking
      rankings << user_ranking
      rankings.sort! { |a, b| b <=> a }
      difference = rankings[0] - rankings[1]
      team_result = {
                      the_team: Team.find_by_id(team.id),
                      ranking_difference: difference
                    }
      ranking_differences << team_result
    end
    # sort an array of hash by ranking_difference
    ranked_teams = ranking_differences.sort_by! { |computed_team_result| computed_team_result[:ranking_difference] }
    final_ranked_teams = []
    ranked_teams.each do |team|
      final_ranked_teams << team[:the_team]
    end
    @suggested_teams = final_ranked_teams
  end
end

app/views/dashboards/_request-game-notification.html.erb
<div class="background-dashboard">
  <div class="container">
    <div class="row dashboard-flex">
      <div class="col-md-6">
        <div class="dashboard-game dashboard-game-request">
          <% if current_user.team.games.count + current_user.requests.where(status: "accepted").count == 1 %>
            <h3>One upcoming game</h3>
          <% elsif current_user.team.games.count + current_user.requests.where(status: "accepted").count == 0 %>
            <h3 class="text-center">Upcoming games</h3>
            <% if current_user.team.requests.where(status: "pending").count == 0 %>
              <p class="text-center">You have no game coming up.
              Try inviting a team!</p>
              <%= link_to "Find a team", teams_path, class: "my-btn" %>
            <% else %>
              <p class="text-center">You have no game coming up, and you have <%= current_user.team.requests.where(status: "pending").count %> pending requests. Try replying to a request!</p>
            <% end %>
          <% else %>
            <h3 class="text-center"><%= current_user.team.games.count + current_user.requests.where(status: "accepted").count %> upcoming games - <%= link_to "SEE ALL", team_games_path(current_user.team), class: "pink-link" %></h3>
            <h5 class="text-center">Next game</h5>
          <% end %>
          <!-- games for requests i've received -->
          <% if current_user.team.games.present? %>
            <p class="text-center">
              Against: <span class="team-game-bold"><%= current_user.team.games.last.request.user.team.name %> - <%= current_user.team.games.last.request.user.team.league.name %></span>
            </p>
            <p class="text-center">
              Dates: from <%= current_user.team.games.last.start_date.strftime('%a %d %b %Y') %> to <%= current_user.team.games.last.end_date.strftime('%a %d %b %Y') %>
            </p>
            <p class="text-center">
              Location:
              <% if current_user.team.requests.last.at_home == false %>
                <%= current_user.team.league.city %>, <%= current_user.team.league.country %> (away)
              <% else %>
                <%= current_user.team.requests.last.team.league.city %>, <%= current_user.team.requests.last.team.league.country %> (home)
              <% end %>
            </p>
            <p class="text-center"><%= link_to "EVENT DETAILS", team_game_path(current_user.team, current_user.team.games.last), class: "my-btn" %></p>
          <!-- games for requests i've sent -->
          <% elsif current_user.requests.where(status: "accepted").present? %>
            <p class="text-center">Against: <%= current_user.requests.where(status: "accepted").last.team.name %> - <%= current_user.requests.where(status: "accepted").last.team.league.name %></p>
            <p class="text-center">Dates: from <%= current_user.requests.where(status: "accepted").last.start_date.strftime('%a %d %b %Y') %> to <%= current_user.requests.where(status: "accepted").last.end_date.strftime('%a %d %b %Y') %></p>
            <p>
              Location:
              <% if current_user.requests.where(status: "accepted").last.at_home == true %>
                <%= current_user.team.league.city %>, <%= current_user.team.league.country %> (home)
              <% else %>
                <%= current_user.requests.where(status: "accepted").last.team.league.city %>, <%= current_user.requests.where(status: "accepted").last.team.league.country %> (away)
              <% end %>
            </p>
            <p class="text-center"><%= link_to "EVENT DETAILS", team_game_path(current_user.team, current_user.requests.where(status: "accepted").last.game), class: "my-btn" %></p>
          <% end %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="dashboard-request dashboard-game-request">
          <div class="request-title">
            <% if current_user.team.requests.where(status: "pending").count == 1 %>
              <h3 class="text-center">One pending request</h3>
            <% elsif current_user.team.requests.where(status: "pending").count == 0 %>
              <h3 class="text-center">Pending requests</h3>
            <% else %>
              <h3 class="text-center"><%= current_user.team.requests.where(status: "pending").count %> pending requests - <%= link_to "SEE ALL", team_requests_path(current_user.team), class: "pink-link" %></h3>
            <% end %>
          </div>
          <% if current_user.team.requests.where(status: "pending").last.present? %>
            <div class="last-request">
              <h5 class="text-center">Last request received</h5>
              <p class="text-center">From: <%= current_user.team.requests.where(status: "pending").last.user.team.name %> - <%= current_user.team.requests.where(status: "pending").last.user.team.league.name %></p>
              <p class="text-center">Dates: from <%= current_user.team.requests.where(status: "pending").last.start_date %> to <%= current_user.team.requests.where(status: "pending").last.start_date %></p>
              <p class="text-center">Location:
                <% if current_user.team.requests.where(status: "pending").last.at_home == false %>
                  <%= current_user.team.league.city %>, <%= current_user.team.league.country %> (away)
                <% else %>
                  <%= current_user.team.requests.where(status: "pending").last.team.league.city %>, <%= current_user.team.requests.where(status: "pending").last.team.league.country %> (home)
                <% end %>
              </p>
              <p class="text-center"><%= link_to "SEE DETAILS", team_request_path(current_user.team, current_user.team.requests.where(status: "pending").last ), class: "my-btn" %></p>
              <br>
          <% else %>
            <p class="text-center">You have no pending request, but you can always invite a team!</p>
            <%= link_to "FIND A TEAM", teams_path, class: "my-btn" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<h2 class="text-center dashboard-title white">Welcome <%= current_user.derby_name %>!</h2>
<div class="container dashboard-container">
  <div class="row">
    <div class="col-md-4">
      <div class="card-category">
        <div class="team-name-ranking">
          <div class="team-name text-center">
            <h2><%= current_user.team.league.name.upcase %></h2>
            <p><%= current_user.team.name %></p>
          </div>
          <div class="star-ranking">
            </p>
          </div>
        </div>
        <div class="card-img logo-img">
          <p><%= cl_image_tag(current_user.team.photo, height: 250, width: 250,crop: :fill, class: 'logo') %></p>
        </div>
        <div class="team-content text-center">
          <p class="ranking">#<%= current_user.team.ranking %>
        </div>
      </div>
    </div>

    <div class="col-md-8">
      <div class="sample-dashboard-center">
        <h3 class="text-center title-dashboard-sample">Suggested opponents: Find a challenger</h3>
        <div class="team-sample">
          <div class="row center-team-sample">
            <div class="col-xs-11 col-sm-11 col-md-11">
              <% @team_one = @suggested_teams.first %>
              <%=  link_to team_path(@team_one), class: "card-link" do %>
              <div class="card-dashboard team-dashboard hover-search">
                <div class="name-photo">
                  <div class="logo-img-team">
                    <%= cl_image_tag @team_one.photo, class: "avatar-large avatar-margin" %>
                  </div>
                  <div class="team-index-card team-name-location">
                    <p class="teams-index-name"><%= @team_one.league.name.upcase %></p>
                    <p><%= @team_one.name %></p>
                    <p class="team-index-location"><i class="fas fa-map-marker-alt"></i> <%= @team_one.league.city %>, <%= @team_one.league.country %></p>
                  </div>
                  </div>
                <div class="suggested-team-ranking">
                  <p class="teams-index-ranking text-center"><span class="pink-ranking">#<%= @team_one.ranking %></span></p>
                </div>
              </div>
              <% end %>
            </div>
            <div class="col-xs-11 col-sm-11 col-md-11">
              <% @team_two = @suggested_teams.second %>
              <%=  link_to team_path(@team_two), class: "card-link" do %>
              <div class="card-dashboard team-dashboard hover-search">
                <div class="name-photo">
                  <div class="logo-img-team">
                    <%= cl_image_tag @team_two.photo, class: "avatar-large avatar-margin" %>
                  </div>
                  <div class="team-index-card team-name-location">
                    <p class="teams-index-name"><%= @team_two.league.name.upcase %></p>
                    <p><%= @team_two.name %></p>
                    <p class="team-index-location"><i class="fas fa-map-marker-alt"></i> <%= @team_two.league.city %>, <%= @team_two.league.country %></p>
                  </div>
                </div>

                <div class="suggested-team-ranking">
                  <p class="teams-index-ranking text-center"><span class="pink-ranking">#<%= @team_two.ranking %></span></p>
                </div>
              </div>
              <% end %>
            </div>
            <div class="col-xs-11 col-sm-11 col-md-11">
              <% @team_three = @suggested_teams.third %>
              <%=  link_to team_path(@team_three), class: "card-link" do %>
              <div class="card-dashboard team-dashboard hover-search">
                <div class="name-photo">
                  <div class="logo-img-team">
                    <%= cl_image_tag @team_three.photo, class: "avatar-large avatar-margin" %>
                  </div>
                  <div class="team-index-card team-name-location">
                    <p class="teams-index-name"><%= @team_three.league.name.upcase %></p>
                    <p><%= @team_three.name %></p>
                    <p class="team-index-location"><i class="fas fa-map-marker-alt"></i> <%= @team_three.league.city %>, <%= @team_three.league.country %></p>
                  </div>

                </div>

                <div class="suggested-team-ranking">
                  <p class="teams-index-ranking text-center"><span class="pink-ranking">#<%= @team_three.ranking %></span></p>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
            <p class="text-right margin-btn">
            <%= link_to "FIND ANOTHER TEAM", teams_path, class: "my-btn sample-btn" %>
            </p>
      </div>
    </div>
  </div>
</div>